name: Déployer sur GitHub Pages

on:
  push:
    branches:
      - main  # Changez ceci par votre branche par défaut si ce n'est pas 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Sinon, le jeton utilisé sera le GITHUB_TOKEN au lieu de votre token personnel (PAT)

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Vous pouvez spécifier la version dont vous avez besoin

      - name: Installer les dépendances
        run: npm install  # Installe les dépendances du projet

      - name: Construire le projet
        run: npm run build  # Construit le projet

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token GitHub pour authentifier
          publish_dir: ./dist  # C'est le répertoire où Vue.js construit votre projet
          publish_branch: gh-pages  # C'est la branche où le site sera déployé





git init
git add .
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/mohamedamineameur/library2.git
git push -u origin main
